_base_: 'default.yml'
data:
  text_aug:
    multi_label: 5
    pre_generated_nouns: false
    generate_prompt_for_np: true
    word_type: 'noun_phrase'

checkpoint:
  key_mapper: '' #/home/sharmaa/groupvit/GroupViT/configs/key_mapper_gs1.yml'
train:
  start_epoch: 0
  epochs: 75
  warmup_epochs: 1
  
  base_lr: 1.6e-3
  warmup_lr: 4e-4
  min_lr: 4e-5
  lr_scaling: 1 # GroupVIT linearly scales the learning rate.
  #If this field is set, default scaling will be replaced by scaling with this unit
  lr_scheduler:
    name: cosine
    t_mul: 1
    cycle_limit: 2
    decay_epochs: 30
  finetune:
    only_grouping: true
    freeze_text_encoder: false

model:
  type: MultiLabelContrastive
  img_encoder:
    type: GroupViT
    embed_dim: 384
    num_heads: [6, 6]
    embed_factors: [1, 1]
    depths: [6, 6]
    num_group_tokens: [64, 0]
    num_output_groups: [64]
    drop_rate: 0.0
    drop_path_rate: 0.1
  text_encoder:
    type: TextTransformer
    context_length: 77
    width: 256
    layers: 12
    vocab_size: 49408
  contrast_temperature: 0.07
  proj_num_layers: 2
  output_dim: 256
  multi_label: ${data.text_aug.multi_label}
