#key to value mapping
modified:
  layers.1.downsample: layers.0.downsample
  
  layers.1.group_token: layers.0.group_token
  #can't be loaded due to shape mismatch 
  layers.1.group_projector: layers.0.group_projector
  layers.2.blocks: layers.1.blocks