#key to value mapping
modified:
  layers.0.blocks.4: layers.1.blocks.0
  layers.0.blocks.5: layers.1.blocks.1
  layers.1.blocks: layers.2.blocks
  layers.2.blocks: layers.3.blocks
#value to key mapping
addas:
  layers.2.downsample: layers.1.downsample
  layers.2.group_token: layers.1.group_token
  #can't be loaded due to shape mismatch 
  layers.2.group_projector: layers.1.group_projector